---
title: "Speeded Categorization: Graphs for Accuracy"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

# load the full processed file, because the outliter removed file only includes 
# inaccurate participants
d <- read.csv("../../data/sc_processed.csv")


```

## Summary Stats
```{r}
agr <- d %>% 
  group_by(Task) %>% 
  summarize(MeanAccuracy = mean(Accuracy),
            SD = sd(Accuracy))
print(agr)
```



# Graph Accuracy by Word


## Overall Accuracy

```{r}
agr <- d %>% 
  group_by(Task) %>% 
  reframe(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy, fill=Task)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))

```

```{r}
agr <- d %>% 
  group_by(Task,BlockOrder) %>% 
  reframe(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy, fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))

```

## Mean Accuracy by Word / Task
Looking at only the first block
```{r,fig.width=10, fig.height=5}
agr <- d %>%
  group_by(Task,Word,BlockOrder) %>% 
  filter((Task == "Valence") & (BlockOrder == "VC") | 
           (Task == "Concrete") & (BlockOrder == "CV")) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
  
agrr <- agr %>% 
  group_by(Word,Task) %>% 
  select(Word,Task,MeanAccuracy) %>% 
  unique()

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy,fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~Word,ncol=10) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
```


# PropPositive and PropConcrete

```{r}
val <- d %>% 
  filter(Task == "Valence") %>% 
  group_by(Word,ConcValCombo) %>%
  # Convert to numeric and subtract 1
  mutate(Response.n = as.numeric(factor(Response, levels = c("negative", "positive"))) - 1) %>%  
  summarize(PropPositive = mean(Response.n))

dodge = position_dodge(.9)
ggplot(data=val, aes(x=reorder(Word,PropPositive),y=PropPositive,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


```{r}
conc <- d %>% 
  filter(Task == "Concrete") %>% 
  group_by(Word,ConcValCombo) %>%
  # Convert to numeric and subtract 1
  mutate(Response.n = as.numeric(factor(Response, levels = c("abstract", "concrete"))) - 1) %>%  
  summarize(PropConcrete = mean(Response.n))

dodge = position_dodge(.9)
ggplot(data=conc, aes(x=reorder(Word,PropConcrete),y=PropConcrete,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


## Accuracy by Participant

```{r,fig.width=10, fig.height=5}
agr <- d %>%
  select(ID.true,Task,Accuracy) %>% 
  group_by(ID.true,Task) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(ID.true,MeanAccuracy),y=MeanAccuracy,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")

```


# Mean Accuracy by ConcValCombo

```{r}
agr <- d %>%
  group_by(Task,ConcValCombo) %>% 
  summarize(MeanAccuracy = mean(Accuracy), CILow = ci.low(Accuracy), CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Task) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```

