---
title: 'Preprocessing: Speeded Categorization'
author: "author"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")
```

# Introduction

Pre-processing from PcIbex. PCIbex makes a handy fuction available to read the raw data from their platform into something more user-friendly.

```{r}
read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

# Read in the results
vc.a <- read.pcibex("../../data/sc_results_prod_VC_A.csv")
vc.a["BlockOrder"] <- "VC"
vc.a["Group"] <- "A"
length(unique(vc.a$MD5.hash.of.participant.s.IP.address))

vc.b <- read.pcibex("../../data/sc_results_prod_VC_B.csv")
vc.b["BlockOrder"] <- "VC"
vc.b["Group"] <- "B"
length(unique(vc.b$MD5.hash.of.participant.s.IP.address))

cv.a <- read.pcibex("../../data/sc_results_prod_CV_A.csv")
cv.a["BlockOrder"] <- "CV"
cv.a["Group"] <- "A"
length(unique(cv.a$MD5.hash.of.participant.s.IP.address))

cv.b <- read.pcibex("../../data/sc_results_prod_CV_B.csv")
cv.b["BlockOrder"] <- "CV"
cv.b["Group"] <- "B"
length(unique(cv.b$MD5.hash.of.participant.s.IP.address))


# Read-in the file with the word feature values of interest
facts <- read.csv("../../data/sc_word_list.csv")
names(facts)
# Create a new column that has the combination of feature values in case we want to look at that later
# facts["ConcValCombo"] <- paste(facts$Concreteness,facts$Valence,sep="-")
names(facts)[names(facts) == "Words"] <- "Word"


# Combine all the dfs together
d <- rbind(vc.a, cv.a, vc.b, cv.b)

d <- d %>% 
  left_join(facts, by="Word")

names(d)
length(unique(d$MD5.hash.of.participant.s.IP.address))
```


# Add necessary columns

```{r}
View(d)
# get the IDs in the right way

d["ID.true"] = d["MD5.hash.of.participant.s.IP.address"]


# Add a Response column# Add a Response column
d$Response <- ""
d$Response <- ifelse(d$Parameter == "Selection", d$Value, d$Response)

# Create the Accuracy column checking if Response is a substring of ConcValCombo
d$Response <- as.character(d$Response)
d$ConcValCombo <- as.character(d$ConcValCombo)

d$Accuracy <- mapply(function(response, pattern) {
  ifelse(grepl(response, pattern), 1, 0)
}, d$Response, d$ConcValCombo)


# Add Task column
d$Task <- ifelse(d$Label == "test_val", "Valence", 
                 ifelse(d$Label == "test_conc", "Concrete", "Na"))

View(d)
# Subset to only test items 
d <- d %>% 
    filter(Label %in% c("test_conc","test_val")) %>%
    dplyr::select(ID.true,Word,ConcValCombo,Task,BlockOrder,Group,Response,Accuracy,ReactionTime) %>%
    # filter out cases where "Response" has no value
    filter(Response != "" ) 


d$ReactionTime <- as.numeric(d$ReactionTime)
d$LogReactionTime <- log(d$ReactionTime)



# Write to .csv
write.csv(d,"../../data/sc_processed.csv")

```

