---
title: "Projection judgments W&R stimuli: Graphs"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(sciplot)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
vaPalette <- c("#FCC6BB", "#F54927", "#9C2007", "#440E03")
gPal <- c("#B9E615","#5E15E6","#F78D02", "#009E73")

# scale_fill_manual(values = vaPalette)
# valPal <- c("#F4320B")

this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

d <- read.csv("../data/03_projection_slider/proj_processed.csv")
```


## Summary Stats
```{r}
agr <- d %>% 
  group_by(Valence) %>% 
  summarize(MeanPropCertain = mean(Response),
            SD = sd(Response))
print(agr)

sub <- d[!is.na(d$Valence), ]
nrow(sub)
nrow(d)

str(sub)

```

```{r}
ggplot(sub, aes(Response, fill = Valence)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("bad"="#F52731","good"= "#27BEF5", "neutral"="#8E27F5"))


ggplot(sub, aes(Response,fill=Valence)) +
  geom_density(alpha = .5) +
  facet_wrap(~Valence) +
  scale_fill_manual(values = c("bad"="#F52731","good"= "#27BEF5", "neutral"="#8E27F5"))
  # scale_fill_manual(values = vaPalette)
```

```{r}

agr <- sub %>% 
  group_by(Valence) %>% 
  reframe(MeanPropCertain = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropCertain - CILow, 
         YMax = MeanPropCertain + CIHigh)


dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Valence,y=MeanPropCertain,fill=Valence)) +
  geom_bar(position=dodge,stat="identity",color = "black") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  scale_fill_manual(values = c("neutral"="#F54927","bad"= "#FCC6BB", "good"="#9C2007"))

```


```{r}
agr <- sub %>% 
  group_by(TrialType,Valence) %>% 
  reframe(MeanPropCertain = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropCertain - CILow, 
         YMax = MeanPropCertain + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(TrialType,MeanPropCertain),y=MeanPropCertain, fill=Valence)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  scale_fill_manual(values = c("neutral"="#F54927","bad"= "#FCC6BB", "good"="#9C2007"))
```


```{r}
agr <- sub %>% 
  group_by(Valence,Word) %>% 
  reframe(MeanPropCertain = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropCertain - CILow, 
         YMax = MeanPropCertain + CIHigh)
# View(agr)

ggplot(agr, aes(x = reorder(Word,MeanPropCertain), y = MeanPropCertain, fill = Valence)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  scale_fill_manual(values = c("neutral"="#F54927","bad"= "#FCC6BB", "good"="#9C2007")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

