---
title: "Projection judgments W&R stimuli: preprocessing"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")
```


```{r}
read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

# Read in the results
d <- read.pcibex("../../data/03_projection_slider/proj_results_prod.csv")
val <- read.csv("../../data/03_projection_slider/valence-vals.csv")

```


```{r}
# Assign participant number
d$Participant <- as.integer(factor(d$MD5.hash.of.participant.s.IP.address))
length(unique(d$Participant))

# Separate out demographic information
demo <- d %>% 
    filter((Label == "demo") &
             (!Parameter %in% c("_Trial_","_Header_"))) %>% 
    dplyr::select(Participant,Parameter,Value) %>% 
    pivot_wider(
        names_from = Parameter,
        values_from = Value,
        names_prefix = "Demo_"
      )

d.sub <- d %>% 
    filter((Label == "test") &
             (PennElementType == "Scale")) %>% 
    dplyr::select(Participant,Label,Value,TrialNumber,TrialType,Word) %>% 
    rename(Response = Value)

df_combined <- full_join(demo, d.sub, by = "Participant")

# Collapse List-columns, 
# convert c(3, 4, 5) to "3;4;5"
df_combined <- df_combined |>
  dplyr::mutate(across(where(is.list),
                       ~ sapply(., paste, collapse = ";")))

df_combined <- full_join(val,df_combined, by = "Word")
```


```{r}

# Write to .csv not aggregating over participants
write.csv(df_combined,"../../data/03_projection_slider/proj_processed.csv")

```